import = ['~/.config/alacritty/color.toml']

[window]
dynamic_padding = true
decorations = "None"
opacity = 0.65
dynamic_title = false

[scrolling]
history = 50000
multiplier = 3

[font]
normal = { family="monospace" }
size = 12

[mouse]
hide_when_typing = true
