#!/usr/bin/env bash

pid="$HOME/.local/state/bgm/pid"
rm -rf $(dirname $pid)
mkdir -p $(dirname $pid)

function clean() {
    kill $(cat $1)
    rm $1
    exit 0
}

trap "clean $pid" 1 2 3 15

function next() {
    kill $(cat $1)
}

trap "next $pid" 10

while true; do
    find ~/Music/** | shuf | while read line; do
        if [ -d $line ]; then
            continue
        fi
        # hyprctl notify 1 1500 0 "$(basename "$line" | cut -f 1 -d '.')"
        notify-send -t 1500 "$(basename "$line" | cut -f 1 -d '.')"
        ffplay -nodisp -autoexit "$line" >/dev/null 2>&1 &
        echo $! > $pid
        wait $(cat $pid)
    done
done
