# change prefix key
set -g prefix M-a
unbind C-b
bind M-a send-prefix

# colors
set -g @color-fg "#cba6f7"
set -g @color-bg "#313244"

# status line
set -g status-position top
set -g status-style "bg=#{@color-bg}"
set -g status-left " #{?client_prefix,#[fg=#{@color-fg}]◉, }"
set -g status-right "#S  "
set -g window-status-format "#[fg=#{@color-fg}]│#I│  #W  │"
set -g window-status-current-format "#[fg=#{@color-fg}]▐#[fg=#{@color-bg},bg=#{@color-fg}]#I│  #W  #[fg=#{@color-fg},bg=default]▌"
set -g window-status-separator ""

# border
set -g pane-border-style "fg=#{@color-bg}"
set -g pane-active-border-style "fg=#{@color-fg}"
set -g popup-border-style "fg=#{@color-fg}"
set -g popup-border-line "rounded"

# message
set -g message-style "bg=#{@color-fg},fg=#{@color-bg}"
set -g message-command-style "bg=#{@color-fg},fg=#{@color-bg}"

# reload config
bind r source-file ~/.config/tmux/tmux.conf

# one based indexing
set -g base-index 1
bind 0 select-window -t:=10
setw -g pane-base-index 1

# window index reordered on delete
set -g renumber-windows on

# enable mouse
set -g mouse on

# use vim keybindings
set -g mode-keys vi

# popup window
bind h display-popup -w85% -h85% "tmux new-session -A -s scratch"

# do not detach on destroy
set -g detach-on-destroy off

# support kitty protocol
set -g allow-passthrough on

# send focus events
set -g focus-events on

# start new pane and window on same directory
bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# resize pane with vim like keybindings
bind -r M-l resize-pane -R 5
bind -r M-h resize-pane -L 5
bind -r M-j resize-pane -D 5
bind -r M-k resize-pane -U 5

# fast window generating
bind -n M-c new-window -c "#{pane_current_path}"

# fast pane switching
bind -n M-l select-pane -R
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U

# fast window switching
bind -n M-n select-window -n
bind -n M-p select-window -p
bind -n M-1 select-window -t:=1
bind -n M-2 select-window -t:=2
bind -n M-3 select-window -t:=3
bind -n M-4 select-window -t:=4
bind -n M-5 select-window -t:=5
bind -n M-6 select-window -t:=6
bind -n M-7 select-window -t:=7
bind -n M-8 select-window -t:=8
bind -n M-9 select-window -t:=9
bind -n M-0 select-window -t:=10
