shell = { program = "/usr/bin/zsh", args = ["--login"] }
working_directory = "None"
live_config_reload = true
ipc_socket = true

[env]

[window]
dimensions = { columns = 0, lines = 0 }
position = "None"
padding = { x = 0, y = 0 }
dynamic_padding = true
decorations = "None"
opacity = 0.8
# blur = false # only on MacOS/KDE wayland
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = false
class = { instance = "Alacritty", general = "Alacritty" }
decorations_theme_variant = "None"
resize_increments = false
# option_as_alt = "None" # only on MacOS

[scrolling]
history = 100000
multiplier = 3

[font]
normal = { family = "monospace", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 12
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = true

[bell]
animation = "Linear"
duration = 0
color = "#FFFFFF"
command = "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = false

[cursor]
style = { shape = "Block", blinking = "Never" }
vi_mode_style = "None"
blink_interval = 0
blink_timeout = 0
unfocused_hollow = false
thickness = 0

[terminal]
osc52 = "Disabled"

[mouse]
hide_when_typing = true
bindings = [
    { mouse = "Left", action = "None" }
]
