# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  "catppuccin.nvim" = {
    pname = "catppuccin.nvim";
    version = "edefef779ab08ce1a4a404713e3012b0d202bd35";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "nvim";
      rev = "edefef779ab08ce1a4a404713e3012b0d202bd35";
      fetchSubmodules = false;
      sha256 = "sha256-EVTNyE0tkPAAgp55sHjxEGtY25sSqSs9nmI4liPJxm4=";
    };
    date = "2026-08-09";
  };
  ddu-filter-matcher_substring = {
    pname = "ddu-filter-matcher_substring";
    version = "01eae40a1aedec5093d6b20f48441acc8bc4436c";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddu-filter-matcher_substring";
      rev = "01eae40a1aedec5093d6b20f48441acc8bc4436c";
      fetchSubmodules = false;
      sha256 = "sha256-GhlaKrspqJHgW/Brsu6GBTsHk7q6qvREzOmysSX1Mjk=";
    };
    date = "2026-07-11";
  };
  ddu-kind-file = {
    pname = "ddu-kind-file";
    version = "649be2f0eee8296ea7772d1916dceb873feac3ce";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddu-kind-file";
      rev = "649be2f0eee8296ea7772d1916dceb873feac3ce";
      fetchSubmodules = false;
      sha256 = "sha256-vR7TRZrKK4A5tPnZxS3DYo+exvvi71AzvojOccOdYuk=";
    };
    date = "2026-09-12";
  };
  ddu-source-file_rec = {
    pname = "ddu-source-file_rec";
    version = "e4cd38a167bebca453f7244d999267ce66814b1b";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddu-source-file_rec";
      rev = "e4cd38a167bebca453f7244d999267ce66814b1b";
      fetchSubmodules = false;
      sha256 = "sha256-8W6q8irRJsQBA19x/SKs67uDaueNPRb9nso4svQyqTY=";
    };
    date = "2026-07-20";
  };
  ddu-ui-ff = {
    pname = "ddu-ui-ff";
    version = "af04a14c0db390dfeb0be56a3c684ccf57cde4ca";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddu-ui-ff";
      rev = "af04a14c0db390dfeb0be56a3c684ccf57cde4ca";
      fetchSubmodules = false;
      sha256 = "sha256-B8n4xpznP6L0aasYMLOO3FhqMRmorW/JUyMjRPX/77M=";
    };
    date = "2026-09-08";
  };
  "ddu.vim" = {
    pname = "ddu.vim";
    version = "46fbd28f81eb7d940ac8becc68b9d926fb7159c0";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddu.vim";
      rev = "46fbd28f81eb7d940ac8becc68b9d926fb7159c0";
      fetchSubmodules = false;
      sha256 = "sha256-cbjp//YPsBAY8B4vMCqjuUNDxeZPlshvaITAAkn5HnM=";
    };
    date = "2026-08-26";
  };
  "denops.vim" = {
    pname = "denops.vim";
    version = "e82c5a94ca1154b05c9d74d6f6f58c9991b1424f";
    src = fetchFromGitHub {
      owner = "vim-denops";
      repo = "denops.vim";
      rev = "e82c5a94ca1154b05c9d74d6f6f58c9991b1424f";
      fetchSubmodules = false;
      sha256 = "sha256-z9FadzT6Y7vFLLdpFR/Ti/FVPGwED4uEkiNZZOkSkqU=";
    };
    date = "2026-05-15";
  };
  "lean.nvim" = {
    pname = "lean.nvim";
    version = "fdbd4dfc3782644f6fff77c654f599ab61201cab";
    src = fetchFromGitHub {
      owner = "Julian";
      repo = "lean.nvim";
      rev = "fdbd4dfc3782644f6fff77c654f599ab61201cab";
      fetchSubmodules = false;
      sha256 = "sha256-sGJfxbD3Ch4+CJ68V5r9r7u4g7WY4syk1z5MvgElZyk=";
    };
    date = "2026-09-22";
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "a9bb4d5f4276aa5cddc015faa3ecc5a7b5a26b14";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "a9bb4d5f4276aa5cddc015faa3ecc5a7b5a26b14";
      fetchSubmodules = false;
      sha256 = "sha256-9XFik7vpA6ETPQM7KhJR2WZPlBa++Aw2NRr5GUnEmgM=";
    };
    date = "2026-09-26";
  };
  nvim-treesitter = {
    pname = "nvim-treesitter";
    version = "25a9b06a09ea4e10712bec37e7b7d9f423262b91";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "25a9b06a09ea4e10712bec37e7b7d9f423262b91";
      fetchSubmodules = false;
      sha256 = "sha256-J7WpwqpYbwCsmaLWj5hCUpqQyTCb68N3abEQVA9Z81A=";
    };
    date = "2026-09-26";
  };
  tree-sitter-lean = {
    pname = "tree-sitter-lean";
    version = "259a2daf7a699cc047221f1e043e4d045fcd6be2";
    src = fetchFromGitHub {
      owner = "Julian";
      repo = "tree-sitter-lean";
      rev = "259a2daf7a699cc047221f1e043e4d045fcd6be2";
      fetchSubmodules = false;
      sha256 = "sha256-6g9DRLer/GZbGnv0qk8MEMGHJ84PHH/7ty4bbfNFvWw=";
    };
    date = "2026-09-06";
  };
  zsh-syntax-highlighting = {
    pname = "zsh-syntax-highlighting";
    version = "0bfcb582e71d3abe604ce67bc0fe5a21f377507e";
    src = fetchFromGitHub {
      owner = "zsh-users";
      repo = "zsh-syntax-highlighting";
      rev = "0bfcb582e71d3abe604ce67bc0fe5a21f377507e";
      fetchSubmodules = false;
      sha256 = "sha256-6yqlW0AWQ2xzl27OqhGjb4MS7yxKnxzLC4g/6riIhn4=";
    };
    date = "2026-09-17";
  };
}
