# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  "catppuccin.nvim" = {
    pname = "catppuccin.nvim";
    version = "edefef779ab08ce1a4a404713e3012b0d202bd35";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "nvim";
      rev = "edefef779ab08ce1a4a404713e3012b0d202bd35";
      fetchSubmodules = false;
      sha256 = "sha256-EVTNyE0tkPAAgp55sHjxEGtY25sSqSs9nmI4liPJxm4=";
    };
    date = "2026-08-09";
  };
  ddu-filter-matcher_substring = {
    pname = "ddu-filter-matcher_substring";
    version = "01eae40a1aedec5093d6b20f48441acc8bc4436c";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddu-filter-matcher_substring";
      rev = "01eae40a1aedec5093d6b20f48441acc8bc4436c";
      fetchSubmodules = false;
      sha256 = "sha256-GhlaKrspqJHgW/Brsu6GBTsHk7q6qvREzOmysSX1Mjk=";
    };
    date = "2026-07-11";
  };
  ddu-kind-file = {
    pname = "ddu-kind-file";
    version = "649be2f0eee8296ea7772d1916dceb873feac3ce";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddu-kind-file";
      rev = "649be2f0eee8296ea7772d1916dceb873feac3ce";
      fetchSubmodules = false;
      sha256 = "sha256-vR7TRZrKK4A5tPnZxS3DYo+exvvi71AzvojOccOdYuk=";
    };
    date = "2026-09-12";
  };
  ddu-source-file_rec = {
    pname = "ddu-source-file_rec";
    version = "e4cd38a167bebca453f7244d999267ce66814b1b";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddu-source-file_rec";
      rev = "e4cd38a167bebca453f7244d999267ce66814b1b";
      fetchSubmodules = false;
      sha256 = "sha256-8W6q8irRJsQBA19x/SKs67uDaueNPRb9nso4svQyqTY=";
    };
    date = "2026-07-20";
  };
  ddu-ui-ff = {
    pname = "ddu-ui-ff";
    version = "af04a14c0db390dfeb0be56a3c684ccf57cde4ca";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddu-ui-ff";
      rev = "af04a14c0db390dfeb0be56a3c684ccf57cde4ca";
      fetchSubmodules = false;
      sha256 = "sha256-B8n4xpznP6L0aasYMLOO3FhqMRmorW/JUyMjRPX/77M=";
    };
    date = "2026-09-08";
  };
  "ddu.vim" = {
    pname = "ddu.vim";
    version = "46fbd28f81eb7d940ac8becc68b9d926fb7159c0";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddu.vim";
      rev = "46fbd28f81eb7d940ac8becc68b9d926fb7159c0";
      fetchSubmodules = false;
      sha256 = "sha256-cbjp//YPsBAY8B4vMCqjuUNDxeZPlshvaITAAkn5HnM=";
    };
    date = "2026-08-26";
  };
  "denops.vim" = {
    pname = "denops.vim";
    version = "e82c5a94ca1154b05c9d74d6f6f58c9991b1424f";
    src = fetchFromGitHub {
      owner = "vim-denops";
      repo = "denops.vim";
      rev = "e82c5a94ca1154b05c9d74d6f6f58c9991b1424f";
      fetchSubmodules = false;
      sha256 = "sha256-z9FadzT6Y7vFLLdpFR/Ti/FVPGwED4uEkiNZZOkSkqU=";
    };
    date = "2026-05-15";
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "ac9d2f7c4757db6320cab6697fe73e5e8adb2457";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "ac9d2f7c4757db6320cab6697fe73e5e8adb2457";
      fetchSubmodules = false;
      sha256 = "sha256-+p0aJzjdfsUQEqgORJnBaZXKDWqB91ijqGvLwF8dP/Q=";
    };
    date = "2026-09-10";
  };
}
