# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  "catppuccin.nvim" = {
    pname = "catppuccin.nvim";
    version = "edefef779ab08ce1a4a404713e3012b0d202bd35";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "nvim";
      rev = "edefef779ab08ce1a4a404713e3012b0d202bd35";
      fetchSubmodules = false;
      sha256 = "sha256-EVTNyE0tkPAAgp55sHjxEGtY25sSqSs9nmI4liPJxm4=";
    };
    date = "2026-08-09";
  };
  ddc-around = {
    pname = "ddc-around";
    version = "277b926fdb3b642572cc756d52a42f18ac7c6059";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-around";
      rev = "277b926fdb3b642572cc756d52a42f18ac7c6059";
      fetchSubmodules = false;
      sha256 = "sha256-5KT1verDM4My7ow+9nswHPsSUNmdqsyx1H3jd2SKp3k=";
    };
    date = "2026-07-03";
  };
  ddc-converter_remove_overlap = {
    pname = "ddc-converter_remove_overlap";
    version = "685ab33137e50d2c3e7a0f0beb89fd1b2ae81168";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-converter_remove_overlap";
      rev = "685ab33137e50d2c3e7a0f0beb89fd1b2ae81168";
      fetchSubmodules = false;
      sha256 = "sha256-CcJT/jHCuBTNtpQ3lVtF/K0mb2GS7G6UkC8k04cDqc8=";
    };
    date = "2026-06-20";
  };
  ddc-matcher_head = {
    pname = "ddc-matcher_head";
    version = "7a52b2facb97a352fcd900baca1b4efa7b652176";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-matcher_head";
      rev = "7a52b2facb97a352fcd900baca1b4efa7b652176";
      fetchSubmodules = false;
      sha256 = "sha256-toNCobCS9NiLQewXZpKyZvuA3AZ83v/rhUbMkV1WOOQ=";
    };
    date = "2026-06-24";
  };
  ddc-sorter_rank = {
    pname = "ddc-sorter_rank";
    version = "0d58fe698528dfeaf895eb70791c1b5e8a1d2288";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-sorter_rank";
      rev = "0d58fe698528dfeaf895eb70791c1b5e8a1d2288";
      fetchSubmodules = false;
      sha256 = "sha256-0iLK7vdkZ27sMUho3SK7NHh77uL+aLpIjqkSOuKc5j8=";
    };
    date = "2026-07-03";
  };
  ddc-source-lsp = {
    pname = "ddc-source-lsp";
    version = "f25867c80c4ebab19ce4d9d32d85aabd646c8d56";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-source-lsp";
      rev = "f25867c80c4ebab19ce4d9d32d85aabd646c8d56";
      fetchSubmodules = false;
      sha256 = "sha256-a8qc4CR0ZMstGVw+CfF/t0n+CSIJmsg8wII6CaZt4p8=";
    };
    date = "2026-08-11";
  };
  ddc-ui-pum = {
    pname = "ddc-ui-pum";
    version = "0679df221520576d07add3cf4219d478db110801";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-ui-pum";
      rev = "0679df221520576d07add3cf4219d478db110801";
      fetchSubmodules = false;
      sha256 = "sha256-6KRKuovKkYUdtyirZ/UNvtAZzgtVgc+EGVTETq2Hu2U=";
    };
    date = "2026-07-07";
  };
  "ddc.vim" = {
    pname = "ddc.vim";
    version = "372197e8f2a1a04fc7fdace6719d1f67fa5ca31b";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc.vim";
      rev = "372197e8f2a1a04fc7fdace6719d1f67fa5ca31b";
      fetchSubmodules = false;
      sha256 = "sha256-92WzXJAHyGV3iZbairWF8eSZV+xRRq4bsnawDfyb4UA=";
    };
    date = "2026-09-26";
  };
  ddu-filter-matcher_substring = {
    pname = "ddu-filter-matcher_substring";
    version = "01eae40a1aedec5093d6b20f48441acc8bc4436c";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddu-filter-matcher_substring";
      rev = "01eae40a1aedec5093d6b20f48441acc8bc4436c";
      fetchSubmodules = false;
      sha256 = "sha256-GhlaKrspqJHgW/Brsu6GBTsHk7q6qvREzOmysSX1Mjk=";
    };
    date = "2026-07-11";
  };
  ddu-kind-file = {
    pname = "ddu-kind-file";
    version = "649be2f0eee8296ea7772d1916dceb873feac3ce";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddu-kind-file";
      rev = "649be2f0eee8296ea7772d1916dceb873feac3ce";
      fetchSubmodules = false;
      sha256 = "sha256-vR7TRZrKK4A5tPnZxS3DYo+exvvi71AzvojOccOdYuk=";
    };
    date = "2026-09-12";
  };
  ddu-source-file_rec = {
    pname = "ddu-source-file_rec";
    version = "e4cd38a167bebca453f7244d999267ce66814b1b";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddu-source-file_rec";
      rev = "e4cd38a167bebca453f7244d999267ce66814b1b";
      fetchSubmodules = false;
      sha256 = "sha256-8W6q8irRJsQBA19x/SKs67uDaueNPRb9nso4svQyqTY=";
    };
    date = "2026-07-20";
  };
  ddu-ui-ff = {
    pname = "ddu-ui-ff";
    version = "af04a14c0db390dfeb0be56a3c684ccf57cde4ca";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddu-ui-ff";
      rev = "af04a14c0db390dfeb0be56a3c684ccf57cde4ca";
      fetchSubmodules = false;
      sha256 = "sha256-B8n4xpznP6L0aasYMLOO3FhqMRmorW/JUyMjRPX/77M=";
    };
    date = "2026-09-08";
  };
  "ddu.vim" = {
    pname = "ddu.vim";
    version = "46fbd28f81eb7d940ac8becc68b9d926fb7159c0";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddu.vim";
      rev = "46fbd28f81eb7d940ac8becc68b9d926fb7159c0";
      fetchSubmodules = false;
      sha256 = "sha256-cbjp//YPsBAY8B4vMCqjuUNDxeZPlshvaITAAkn5HnM=";
    };
    date = "2026-08-26";
  };
  "denops.vim" = {
    pname = "denops.vim";
    version = "e82c5a94ca1154b05c9d74d6f6f58c9991b1424f";
    src = fetchFromGitHub {
      owner = "vim-denops";
      repo = "denops.vim";
      rev = "e82c5a94ca1154b05c9d74d6f6f58c9991b1424f";
      fetchSubmodules = false;
      sha256 = "sha256-z9FadzT6Y7vFLLdpFR/Ti/FVPGwED4uEkiNZZOkSkqU=";
    };
    date = "2026-05-15";
  };
  "lean.nvim" = {
    pname = "lean.nvim";
    version = "c15b1cea82ccb6c0bc1ee16ec12632fc04219087";
    src = fetchFromGitHub {
      owner = "Julian";
      repo = "lean.nvim";
      rev = "c15b1cea82ccb6c0bc1ee16ec12632fc04219087";
      fetchSubmodules = false;
      sha256 = "sha256-BmAGenhyn4d9Tv0nmcCSgGsWebVSYrAK73dU4iMJa9M=";
    };
    date = "2026-09-27";
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "a9bb4d5f4276aa5cddc015faa3ecc5a7b5a26b14";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "a9bb4d5f4276aa5cddc015faa3ecc5a7b5a26b14";
      fetchSubmodules = false;
      sha256 = "sha256-9XFik7vpA6ETPQM7KhJR2WZPlBa++Aw2NRr5GUnEmgM=";
    };
    date = "2026-09-26";
  };
  nvim-treesitter = {
    pname = "nvim-treesitter";
    version = "728e031f6b11d03d1f0708b7dc4fb0f1d9c8a137";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "728e031f6b11d03d1f0708b7dc4fb0f1d9c8a137";
      fetchSubmodules = false;
      sha256 = "sha256-z6e3Dvp8TQDjTRglfVq0B+7Ejozwnw/zSvpGuSy6rbY=";
    };
    date = "2026-09-27";
  };
  "pum.vim" = {
    pname = "pum.vim";
    version = "c7140bef217dbb6bf8f41e8c649d2c6a8a3d6e05";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "pum.vim";
      rev = "c7140bef217dbb6bf8f41e8c649d2c6a8a3d6e05";
      fetchSubmodules = false;
      sha256 = "sha256-5KsNU842iEa1tm2feJowW4g+JIbfpN5jG4/yjfdyvIQ=";
    };
    date = "2026-09-19";
  };
  tree-sitter-lean = {
    pname = "tree-sitter-lean";
    version = "259a2daf7a699cc047221f1e043e4d045fcd6be2";
    src = fetchFromGitHub {
      owner = "Julian";
      repo = "tree-sitter-lean";
      rev = "259a2daf7a699cc047221f1e043e4d045fcd6be2";
      fetchSubmodules = false;
      sha256 = "sha256-6g9DRLer/GZbGnv0qk8MEMGHJ84PHH/7ty4bbfNFvWw=";
    };
    date = "2026-09-06";
  };
  zsh-syntax-highlighting = {
    pname = "zsh-syntax-highlighting";
    version = "0bfcb582e71d3abe604ce67bc0fe5a21f377507e";
    src = fetchFromGitHub {
      owner = "zsh-users";
      repo = "zsh-syntax-highlighting";
      rev = "0bfcb582e71d3abe604ce67bc0fe5a21f377507e";
      fetchSubmodules = false;
      sha256 = "sha256-6yqlW0AWQ2xzl27OqhGjb4MS7yxKnxzLC4g/6riIhn4=";
    };
    date = "2026-09-17";
  };
}
