[".local/bin/deno"]
    type = "archive-file"
    url = "https://github.com/denoland/deno/releases/latest/download/deno-x86_64-unknown-linux-gnu.zip"
    executable = true
    path = "deno"
    refreshPeriod = "24h"

[".local/bin/tinty"]
    type = "archive-file"
    url = "https://github.com/tinted-theming/tinty/releases/latest/download/tinty-x86_64-unknown-linux-gnu.tar.gz"
    executable = true
    path = "tinty"
    refreshPeriod = "24h"

[".local/bin/eza"]
    type = "archive-file"
    url = "https://github.com/eza-community/eza/releases/latest/download/eza_x86_64-unknown-linux-gnu.zip"
    executable = true
    path = "eza"
    refreshPeriod = "24h"
