vim.cmd.highlight("clear")

if vim.fn.exists("syntax_on") then
    vim.cmd.syntax("reset")
end

vim.g.colors_name = "basecoat"
vim.o.termguicolors = false

local c = {
    black = 0,
    red = 1,
    green = 2,
    brown = 3,
    blue = 4,
    purple = 5,
    cyan = 6,
    light_gray = 7,
    gray = 8,
    light_red = 9,
    light_green = 10,
    yellow = 11,
    light_blue = 12,
    pink = 13,
    light_cyan = 14,
    white = 15,
}

-- :h highlight-groups
vim.api.nvim_set_hl(0, "ColorColumn",{ ctermbg = c.gray })
vim.api.nvim_set_hl(0, "Conceal",{ ctermfg = c.light_gray })
vim.api.nvim_set_hl(0, "CurSearch", { ctermfg = c.black, ctermbg = c.light_red })
vim.api.nvim_set_hl(0, "Cursor", { ctermfg = c.black, ctermbg = c.white })
vim.api.nvim_set_hl(0, "lCursor", { ctermfg = c.black, ctermbg = c.white })
vim.api.nvim_set_hl(0, "CursorIM", { ctermfg = c.black, ctermbg = c.white })
vim.api.nvim_set_hl(0, "CursorColumn", { ctermbg = c.black })
vim.api.nvim_set_hl(0, "CursorLine", { ctermbg = c.black })
vim.api.nvim_set_hl(0, "Directory", { ctermfg = c.blue })
vim.api.nvim_set_hl(0, "DiffAdd", { ctermbg = c.gray })
vim.api.nvim_set_hl(0, "DiffChange", { ctermbg = c.black })
vim.api.nvim_set_hl(0, "DiffDelete", { ctermbg = c.black })
vim.api.nvim_set_hl(0, "DiffText", { ctermbg = c.black })
vim.api.nvim_set_hl(0, "EndOfBuffer", { ctermfg = c.black })
vim.api.nvim_set_hl(0, "TermCursor", { ctermfg = c.white, ctermbg = c.black })
vim.api.nvim_set_hl(0, "TermCursorNC", { ctermfg = c.white, ctermbg = c.black })
vim.api.nvim_set_hl(0, "ErrorMsg", { ctermfg = c.red })
vim.api.nvim_set_hl(0, "WinSeparator", { ctermfg = c.gray })
vim.api.nvim_set_hl(0, "Folded", { ctermfg = c.blue })
vim.api.nvim_set_hl(0, "FoldColumn", { ctermfg = c.light_gray })
vim.api.nvim_set_hl(0, "SignColumn", { ctermfg = c.gray })
vim.api.nvim_set_hl(0, "IncSearch", { ctermfg = c.black, ctermbg = c.cyan })
vim.api.nvim_set_hl(0, "Substitute", { ctermfg = c.light_red, ctermbg = c.gray })
vim.api.nvim_set_hl(0, "LineNr", { ctermfg = c.light_gray })
vim.api.nvim_set_hl(0, "LineNrAbove", { ctermfg = c.light_gray })
vim.api.nvim_set_hl(0, "LineNrBelow", { ctermfg = c.light_gray })
vim.api.nvim_set_hl(0, "CursorLineNr", { ctermfg = c.white, ctermbg = c.black })
vim.api.nvim_set_hl(0, "CursorLineFold", { link = "FoldColumn" })
vim.api.nvim_set_hl(0, "CursorLineSign", { link = "SignColumn" })
vim.api.nvim_set_hl(0, "MatchParen", { ctermfg = c.brown, ctermbg = c.gray })
vim.api.nvim_set_hl(0, "ModeMsg", { ctermfg = c.white })
vim.api.nvim_set_hl(0, "MsgArea", { ctermfg = c.white })
vim.api.nvim_set_hl(0, "MsgSeparator", { ctermfg = c.white })
vim.api.nvim_set_hl(0, "MoreMsg", { ctermfg = c.blue })
vim.api.nvim_set_hl(0, "NonText", { ctermfg = c.light_gray })
vim.api.nvim_set_hl(0, "Normal", { ctermfg = c.white })
vim.api.nvim_set_hl(0, "NormalFloat", { ctermfg = c.white, ctermbg = c.black })
vim.api.nvim_set_hl(0, "FloatBorder", { ctermfg = c.blue })
vim.api.nvim_set_hl(0, "FloatTitle", { ctermfg = c.light_gray })
vim.api.nvim_set_hl(0, "NormalNC", { ctermfg = c.white })
vim.api.nvim_set_hl(0, "Pmenu", { ctermfg = c.light_gray, ctermbg = c.black })
vim.api.nvim_set_hl(0, "PmenuSel", { ctermfg = c.white, ctermbg = c.gray })
vim.api.nvim_set_hl(0, "PmenuKind", { link = "Pmenu" })
vim.api.nvim_set_hl(0, "PmenuKindSel", { link = "PmenuSel" })
vim.api.nvim_set_hl(0, "PmenuExtra", { link = "Pmenu" })
vim.api.nvim_set_hl(0, "PmenuExtraSel", { link = "PmenuSel" })
vim.api.nvim_set_hl(0, "PmenuSbar", { ctermbg = c.gray })
vim.api.nvim_set_hl(0, "PmenuThumb", { ctermbg = c.light_gray })
vim.api.nvim_set_hl(0, "Question", { ctermfg = c.blue })
vim.api.nvim_set_hl(0, "QuickFixLine", { ctermfg = c.white, ctermbg = c.gray })
vim.api.nvim_set_hl(0, "Search", { ctermfg = c.white, ctermbg = c.gray })
vim.api.nvim_set_hl(0, "Specialkey", { link = "NonText" })
vim.api.nvim_set_hl(0, "SpellBad", { ctermfg = c.white, underline = true })
vim.api.nvim_set_hl(0, "SpellCap", { ctermfg = c.white, underline = true })
vim.api.nvim_set_hl(0, "SpellLocal", { ctermfg = c.white, underline = true })
vim.api.nvim_set_hl(0, "SpellRare", { ctermfg = c.white, underline = true })
vim.api.nvim_set_hl(0, "StatusLine", { ctermfg = c.white, ctermbg = c.black })
vim.api.nvim_set_hl(0, "StatusLineNC", { ctermfg = c.black })
vim.api.nvim_set_hl(0, "TabLine", { ctermfg = c.light_gray, ctermbg = c.black })
vim.api.nvim_set_hl(0, "TabLineFill", { ctermfg = c.white })
vim.api.nvim_set_hl(0, "TabLineSel", { ctermfg = c.light_green, ctermbg = c.gray })
vim.api.nvim_set_hl(0, "Title", { ctermfg = c.blue })
vim.api.nvim_set_hl(0, "Visual", { ctermbg = c.gray })
vim.api.nvim_set_hl(0, "VisualNOS", { ctermbg = c.gray })
vim.api.nvim_set_hl(0, "WarningMsg", { ctermfg = c.yellow })
vim.api.nvim_set_hl(0, "Whitespace", { ctermfg = c.light_gray })
vim.api.nvim_set_hl(0, "WildMenu", { ctermbg = c.gray })
vim.api.nvim_set_hl(0, "WinBar", { ctermfg = c.brown })
vim.api.nvim_set_hl(0, "WinBarNC", { link = "WinBar" })

-- :h group-name
vim.api.nvim_set_hl(0, "Comment", { ctermfg = c.light_gray })
vim.api.nvim_set_hl(0, "Constant", { ctermfg = c.brown })
vim.api.nvim_set_hl(0, "String", { ctermfg = c.green })
vim.api.nvim_set_hl(0, "Character", { ctermfg = c.light_green })
vim.api.nvim_set_hl(0, "Number", { ctermfg = c.brown })
vim.api.nvim_set_hl(0, "Boolean", { ctermfg = c.brown })
vim.api.nvim_set_hl(0, "Float", { ctermfg = c.brown })
vim.api.nvim_set_hl(0, "Identifier", { ctermfg = c.pink })
vim.api.nvim_set_hl(0, "Function", { ctermfg = c.blue })
vim.api.nvim_set_hl(0, "Statement", { ctermfg = c.purple })
vim.api.nvim_set_hl(0, "Conditional", { ctermfg = c.purple })
vim.api.nvim_set_hl(0, "Repeat", { ctermfg = c.purple })
vim.api.nvim_set_hl(0, "Label", { ctermfg = c.cyan })
vim.api.nvim_set_hl(0, "Operator", { ctermfg = c.light_green })
vim.api.nvim_set_hl(0, "Keyword", { ctermfg = c.purple })
vim.api.nvim_set_hl(0, "Exception", { ctermfg = c.purple })
vim.api.nvim_set_hl(0, "PreProc", { ctermfg = c.pink })
vim.api.nvim_set_hl(0, "Include", { ctermfg = c.purple })
vim.api.nvim_set_hl(0, "Define", { ctermfg = c.purple })
vim.api.nvim_set_hl(0, "Macro", { ctermfg = c.purple })
vim.api.nvim_set_hl(0, "PreCondit", { link = "PreProc" })
vim.api.nvim_set_hl(0, "Type", { ctermfg = c.yellow })
vim.api.nvim_set_hl(0, "StorageClass", { ctermfg = c.yellow })
vim.api.nvim_set_hl(0, "Structure", { ctermfg = c.yellow })
vim.api.nvim_set_hl(0, "Typedef", { link = "Type" })
vim.api.nvim_set_hl(0, "Special", { ctermfg = c.pink })
vim.api.nvim_set_hl(0, "SpecialChar", { link = "Special" })
vim.api.nvim_set_hl(0, "Tag", { ctermfg = c.light_blue })
vim.api.nvim_set_hl(0, "Delimiter", { ctermfg = c.light_gray })
vim.api.nvim_set_hl(0, "SpecialComment", { link = "Special" })
vim.api.nvim_set_hl(0, "Debug", { link = "Special" })
vim.api.nvim_set_hl(0, "Underlined", { underline = true })
vim.api.nvim_set_hl(0, "Ignore", { ctermfg = c.black })
vim.api.nvim_set_hl(0, "Error", { ctermfg = c.red })
vim.api.nvim_set_hl(0, "Todo", { ctermfg = c.black, ctermbg = c.pink })

-- https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md
vim.api.nvim_set_hl(0, "@variable", { ctermfg = c.white })
vim.api.nvim_set_hl(0, "@variable.builtin", { ctermfg = c.red })
vim.api.nvim_set_hl(0, "@variable.parameter", { ctermfg = c.light_red })
vim.api.nvim_set_hl(0, "@variable.member", { ctermfg = c.white })
vim.api.nvim_set_hl(0, "@constant", { ctermfg = c.brown })
vim.api.nvim_set_hl(0, "@constant.builtin", { ctermfg = c.brown })
vim.api.nvim_set_hl(0, "@constant.macro", { ctermfg = c.purple })
vim.api.nvim_set_hl(0, "@module", { ctermfg = c.light_blue })
vim.api.nvim_set_hl(0, "@module.builtin", { ctermfg = c.light_blue })
vim.api.nvim_set_hl(0, "@label", { link = "Label" })
vim.api.nvim_set_hl(0, "@string", { link = "String" })
vim.api.nvim_set_hl(0, "@string.documentation", { link = "String" })
vim.api.nvim_set_hl(0, "@string.regexp", { ctermfg = c.brown })
vim.api.nvim_set_hl(0, "@string.escape", { ctermfg = c.pink })
vim.api.nvim_set_hl(0, "@string.special", { link = "Special" })
vim.api.nvim_set_hl(0, "@string.special.symbol", { ctermfg = c.pink })
vim.api.nvim_set_hl(0, "@string.special.url", { ctermfg = c.pink, underline = true })
vim.api.nvim_set_hl(0, "@string.special.path", { ctermfg = c.pink, underline = true })
vim.api.nvim_set_hl(0, "@character", { link = "Character" })
vim.api.nvim_set_hl(0, "@character.special", { link = "SpecialChar" })
vim.api.nvim_set_hl(0, "@boolean", { link = "Boolean" })
vim.api.nvim_set_hl(0, "@number", { link = "Number" })
vim.api.nvim_set_hl(0, "@number.float", { link = "Float" })
vim.api.nvim_set_hl(0, "@type", { link = "Type" })
vim.api.nvim_set_hl(0, "@type.builtin", { link = "Type" })
vim.api.nvim_set_hl(0, "@type.definition", { link = "Type" })
vim.api.nvim_set_hl(0, "@type.qualifier", { link = "Keyword" })
vim.api.nvim_set_hl(0, "@attribute", { link = "Constant" })
vim.api.nvim_set_hl(0, "@property", { ctermfg = c.light_blue })
vim.api.nvim_set_hl(0, "@function", { link = "Function" })
vim.api.nvim_set_hl(0, "@function.builtin", { ctermfg = c.brown })
vim.api.nvim_set_hl(0, "@function.call", { ctermfg = c.blue })
vim.api.nvim_set_hl(0, "@function.macro", { ctermfg = c.light_cyan })
vim.api.nvim_set_hl(0, "@function.method", { link = "Function" })

vim.api.nvim_set_hl(0, "@lsp.type.variable", { link = "@variable" })
vim.api.nvim_set_hl(0, "@lsp.type.variable.builtin", { link = "@variable.builtin" })
vim.api.nvim_set_hl(0, "@lsp.type.variable.parameter", { link = "@variable.parameter" })
vim.api.nvim_set_hl(0, "@lsp.type.variable.member", { link = "@variable.member" })
vim.api.nvim_set_hl(0, "@lsp.type.constant", { link = "@constant" })
vim.api.nvim_set_hl(0, "@lsp.type.constant.builtin", { link = "@constant.builtin" })
vim.api.nvim_set_hl(0, "@lsp.type.constant.macro", { link = "@constant.macro" })
vim.api.nvim_set_hl(0, "@lsp.type.module", { link = "@module" })
vim.api.nvim_set_hl(0, "@lsp.type.module.builtin", { link = "@module.builtin" })
vim.api.nvim_set_hl(0, "@lsp.type.label", { link = "@label" })
vim.api.nvim_set_hl(0, "@lsp.type.string", { link = "@string" })
vim.api.nvim_set_hl(0, "@lsp.type.string.documentation", { link = "@string.documentation" })
vim.api.nvim_set_hl(0, "@lsp.type.string.regexp", { link = "@string.regexp" })
vim.api.nvim_set_hl(0, "@lsp.type.string.escape", { link = "@string.escape" })
vim.api.nvim_set_hl(0, "@lsp.type.string.special", { link = "@string.special" })
vim.api.nvim_set_hl(0, "@lsp.type.string.special.symbol", { link = "@string.special.symbol" })
vim.api.nvim_set_hl(0, "@lsp.type.string.special.url", { link = "@string.special.url" })
vim.api.nvim_set_hl(0, "@lsp.type.string.special.path", { link = "@string.special.path" })
vim.api.nvim_set_hl(0, "@lsp.type.character", { link = "@character" })
vim.api.nvim_set_hl(0, "@lsp.type.character.special", { link = "@character.special" })
vim.api.nvim_set_hl(0, "@lsp.type.boolean", { link = "@boolean" })
vim.api.nvim_set_hl(0, "@lsp.type.number", { link = "@number" })
vim.api.nvim_set_hl(0, "@lsp.type.number.float", { link = "@number.float" })
vim.api.nvim_set_hl(0, "@lsp.type.type", { link = "@type" })
vim.api.nvim_set_hl(0, "@lsp.type.type.builtin", { link = "@type.builtin" })
vim.api.nvim_set_hl(0, "@lsp.type.type.definition", { link = "@type.definition" })
vim.api.nvim_set_hl(0, "@lsp.type.type.qualifier", { link = "@type.qualifier" })
vim.api.nvim_set_hl(0, "@lsp.type.attribute", { link = "@attribute" })
vim.api.nvim_set_hl(0, "@lsp.type.property", { link = "@property" })
vim.api.nvim_set_hl(0, "@lsp.type.function", { link = "@function" })
vim.api.nvim_set_hl(0, "@lsp.type.function.builtin", { link = "@function.builtin" })
vim.api.nvim_set_hl(0, "@lsp.type.function.call", { link = "@function.call" })
vim.api.nvim_set_hl(0, "@lsp.type.function.macro", { link = "@function.macro" })
vim.api.nvim_set_hl(0, "@lsp.type.function.method", { link = "@function.method" })

-- https://github.com/nvim-telescope/telescope.nvim/blob/master/plugin/telescope.lua
vim.api.nvim_set_hl(0, "TelescopeSelection", { ctermfg = c.white, ctermbg = c.gray })
vim.api.nvim_set_hl(0, "TelescopeSelectionCaret", { ctermfg = c.light_red, ctermbg = c.gray })
vim.api.nvim_set_hl(0, "TelescopeMultiSelection", { ctermfg = c.white, ctermbg = c.gray })
vim.api.nvim_set_hl(0, "TelescopeMultiIcon", { ctermfg = c.light_red, ctermbg = c.gray })
vim.api.nvim_set_hl(0, "TelescopeNormal", { ctermfg = c.white, ctermbg = c.black })
vim.api.nvim_set_hl(0, "TelescopePreviewNormal", { link = "TelescopeNormal" })
vim.api.nvim_set_hl(0, "TelescopePromptNormal", { link = "TelescopeNormal" })
vim.api.nvim_set_hl(0, "TelescopeResultsNormal", { ctermfg = c.light_gray, ctermbg = c.black })
vim.api.nvim_set_hl(0, "TelescopeBorder", { link = "TelescopeNormal" })
vim.api.nvim_set_hl(0, "TelescopePromptBorder", { link = "TelescopeBorder" })
vim.api.nvim_set_hl(0, "TelescopeResultsBorder", { link = "TelescopeBorder" })
vim.api.nvim_set_hl(0, "TelescopePreviewBorder", { link = "TelescopeBorder" })
vim.api.nvim_set_hl(0, "TelescopeTitle", { ctermfg = c.black, ctermbg = c.brown })
vim.api.nvim_set_hl(0, "TelescopePromptTitle", { link = "TelescopeTitle" })
