#!/usr/bin/env bash

pid="$HOME/.local/state/bgm/pid"
if [ ! -d $(dirname $pid) ]; then
    rm -rf $(dirname $pid)
    mkdir -p $(dirname $pid)
fi

function clean() {
    kill $(cat $1)
    rm $1
    exit 0
}

trap "clean $pid" 1 2 3 15

function next() {
    kill $(cat $1)
}

trap "next $pid" 10

while true; do
    find ~/Music/** | shuf | while read line; do
        ffplay -nodisp -autoexit "$line" >/dev/null 2>&1 &
        echo $! > $pid
        wait $(cat $pid)
    done
done
