[catppuccin]
type = "git"
path = "~/.local/share/nvim/site/pack/plugins/start/catppuccin"
url = "https://github.com/catppuccin/nvim.git"

[plenary]
type = "git"
path = "~/.local/share/nvim/site/pack/plugins/start/plenary.nvim"
url = "https://github.com/nvim-lua/plenary.nvim.git"

[denops]
type = "git"
path = "~/.local/share/nvim/site/pack/plugins/start/denops.nvim"
url = "https://github.com/vim-denops/denops.vim.git"

[telescope-nvim]
type = "git"
path = "~/.local/share/nvim/site/pack/plugins/start/telescope.nvim"
url = "https://github.com/nvim-telescope/telescope.nvim.git"

[nvim-treesitter]
type = "git"
path = "~/.local/share/nvim/site/pack/plugins/start/nvim-treesitter"
url = "https://github.com/nvim-treesitter/nvim-treesitter.git"

[nvim-lspconfig]
type = "git"
path = "~/.local/share/nvim/site/pack/plugins/start/nvim-lspconfig"
url = "https://github.com/neovim/nvim-lspconfig.git"

[skkeleton]
type = "git"
path = "~/.local/share/nvim/site/pack/plugins/start/skkeleton"
url = "https://github.com/vim-skk/skkeleton.git"

[nvim-cmp]
type = "git"
path = "~/.local/share/nvim/site/pack/plugins/start/nvim-cmp"
url = "https://github.com/hrsh7th/nvim-cmp.git"

[cmp-nvim-lsp]
type = "git"
path = "~/.local/share/nvim/site/pack/plugins/start/cmp-nvim-lsp"
url = "https://github.com/hrsh7th/cmp-nvim-lsp.git"

[cmp-buffer]
type = "git"
path = "~/.local/share/nvim/site/pack/plugins/start/cmp-buffer"
url = "https://github.com/hrsh7th/cmp-buffer.git"

[cmp-path]
type = "git"
path = "~/.local/share/nvim/site/pack/plugins/start/cmp-path"
url = "https://github.com/hrsh7th/cmp-path.git"

[cmp-cmdline]
type = "git"
path = "~/.local/share/nvim/site/pack/plugins/start/cmp-cmdline"
url = "https://github.com/hrsh7th/cmp-cmdline.git"

[cmp-vsnip]
type = "git"
path = "~/.local/share/nvim/site/pack/plugins/start/cmp-vsnip"
url = "https://github.com/hrsh7th/cmp-vsnip.git"

[vim-vsnip]
type = "git"
path = "~/.local/share/nvim/site/pack/plugins/start/vim-vsnip"
url = "https://github.com/hrsh7th/vim-vsnip.git"

[clangd]
type = "script"
path = "~/.local/share/nvim/lsp/clangd"
script = "~/.config/plug/neovim/clangd.sh"

[pyright]
type = "script"
path = "~/.local/share/nvim/lsp/pyright"
script = "~/.config/plug/neovim/pyright.sh"
